---
title: "sc-AML"
author: "EO Karakaslar"
date: "4/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/LUMC/")
```

```{r libraries, warning=FALSE, message=FALSE}
library(plyr)
library(cinaR)
library(dplyr)
library(MuSiC)
library(purrr)
library(xbioc)
library(tidyr)
library(muscat)
library(glmnet)
library(ggpubr)
library(Seurat)
library(readxl)
library(ggprism)
library(ggplot2)
library(viridis)
library(pheatmap)
library(paletteer)
library(slingshot)
library(grDevices)
library(data.table)
library(RColorBrewer)
library(SingleCellExperiment)
library(SummarizedExperiment)

source("utils/CIBERSORT.R")
source("utils/wrangleMat.R")
theme.gg <- theme_bw(base_size = 10) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
cp.pastel <- paletteer_d("rcartocolor::Pastel")
cp.polyco <- paletteer_d("Polychrome::light")
```




Make whole vanGalen data a huge gene by cell matrix and merge their meta data.
```{r load data}
# vanGalen (BM)
# Example file to see what it looks like
count.matrix <- fread("data/vanGalen/GSM3587923_AML1012-D0.dem.txt.gz")

gene.list <- count.matrix[,1]

# list all gene x cell files
cm.paths <- list.files(pattern = "dem", recursive = T)

# list all meta files
meta.paths <- list.files(pattern = "anno", recursive = T)

big.cm <- data.frame(Gene = gene.list)
for (file in cm.paths){
    big.cm <- cbind(big.cm, fread(file, drop = "Gene"))
}

# transfer gene-names to rownames
rownames(big.cm) <- big.cm$Gene
big.cm <- big.cm[,-1]

big.meta <- data.frame()
for (file in meta.paths){
    big.meta <- rbind.fill(big.meta, fread(file, fill = T))
}

rownames(big.meta) <- big.meta[,"Cell"]

# check every cell-id matches the columns
sum(colnames(big.cm) %in% rownames(big.meta)) == nrow(big.meta)

big.meta$Sample <- strsplit(big.meta$Cell, "-", fixed = T) %>% 
    map_chr(1) %>% strsplit("_", fixed = T) %>% 
    map_chr(1)

big.meta$Day <- sapply(big.meta$Cell, function(x){ifelse(grepl("-D",x), 
                                         strsplit(x, "-", fixed = T) %>% 
                                             map_chr(2) %>% 
                                             strsplit("_", fixed = T) %>% 
                                             map_chr(1), NA)})

 
bm.loc <- grepl("BM",big.meta$Sample)
aml.loc <- grepl("AML", big.meta$Sample)

bm.data <- big.cm[,bm.loc] 
bm.meta <- big.meta[bm.loc,]

aml.data <- big.cm[,aml.loc] 
aml.meta <- big.meta[aml.loc,]
```

Yeey, now fun starts! Let's create a Seurat object

```{r move into seurat}
bm <- CreateSeuratObject(counts = bm.data, project = "scAML",meta.data = bm.meta, min.cells = 3, min.features = 200)

Idents(bm) <- "scAML"

bm[["percent.mt"]] <- PercentageFeatureSet(bm, pattern = "^MT-")


VlnPlot(bm, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

# log-normalize
bm <- NormalizeData(bm, normalization.method = "LogNormalize", scale.factor = 1e4)

bm <- FindVariableFeatures(bm, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(bm), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(bm)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)

plot2

# scale
all.genes <- rownames(bm)
bm <- ScaleData(bm, features = all.genes)


bm <- RunPCA(bm, features = VariableFeatures(object = bm))
bm <- RunUMAP(bm, dims = 1:10)

# remove all except seurat object and colors
rm(list=setdiff(ls(), c("bm", "cp.pastel", "cp.polyco", "theme.gg")))
# save some memory
gc()

# remove non-annotated cells
bm <- bm[,bm$CellType != ""]

Idents(bm) <- bm$CellType
pdf("output/VanGalen_healthy_BM_original_cell_types.pdf", width = 5, height = 4)
DimPlot(bm, label = T, pt.size = 1.2, label.size = 2.5, repel = T, shuffle = T) + theme.gg + theme(legend.position = "none")
dev.off()
```

```{r}
pb.sum <- as.data.frame(AggregateExpression(bm, assays = "RNA"))
pb.avg <- as.data.frame(AverageExpression(bm, assays = "RNA"))
colnames(pb.sum) <- unique(Idents(bm))
colnames(pb.avg) <- unique(Idents(bm))

pheatmap(cor(log1p(pb.sum)), cluster_rows = F, cluster_cols = F)
pheatmap(cor(log1p(pb.avg)), cluster_rows = F, cluster_cols = F)

head(log1p(pb.sum))
```



```{r Transfer Label to VanGalen}
WTA <- readRDS("data/Abseq/WTA_projected.rds")

WTA <- Seurat::UpdateSeuratObject(WTA)

DefaultAssay(WTA)    <- "RNA" # RNA in 13165 cells from a healthy young bone marrow donor

WTA <- ScaleData(WTA, verbose = FALSE)
WTA <- RunPCA(WTA, npcs = 30, verbose = FALSE)
WTA <- RunUMAP(WTA, reduction = "pca", dims = 1:30)

pdf("output/Triana_healthy_BM_original_cell_types.pdf", width = 5, height = 4)
DimPlot(WTA,label = T, reduction = "umap", pt.size = 1.2, label.size = 2.5, repel = T, shuffle = F) + theme.gg + theme(legend.position = "none")
dev.off()

unique(Idents(WTA))

WTA.anchors <- FindTransferAnchors(reference = WTA, query = bm, 
    dims = 1:30, reference.reduction = "pca")
predictions <- TransferData(anchorset = WTA.anchors, refdata = Idents(WTA), 
    dims = 1:30)
bm <- AddMetaData(bm, metadata = predictions)

Idents(bm) <- "CellType"
p1 <- DimPlot(bm) + ggtitle("Original labels", subtitle = "Van Galen et al") + theme.gg
Idents(bm) <- "predicted.id"
p2 <- DimPlot(bm) + ggtitle("Query transferred labels", subtitle = "from Triana et al Healthy Sample") + theme.gg

pdf("output/VanGalen_label_transfer_triana.pdf", width = 14, height = 5)
p1 + p2 
dev.off()

```



```{r}
BM_All <- readRDS("data/Abseq/Healthy.rds")

DefaultAssay(BM_All) <- "RNA" # 462 mRNAs in 70017 cells from healthy young, healthy old and leukemic human bone marrow


WTA.anchors <- FindTransferAnchors(reference = WTA, query = BM_All, 
    dims = 1:30, reference.reduction = "pca")
predictions <- TransferData(anchorset = WTA.anchors, refdata = Idents(WTA), 
    dims = 1:30)
BM_All <- AddMetaData(BM_All, metadata = predictions)


DimPlot(BM_All, reduction = "umap", group.by = "predicted.id")

FeaturePlot(BM_All, "CD14")
# remove all except seurat object and colors
rm(list=setdiff(ls(), c("bm", "cp.pastel", "cp.polyco", "theme.gg","BM_All", "WTA")))
# save some memory
gc()


# Meta data wrangling 
bm$study <- "BM_Van_Galen"
BM_All$study <- "BM_ALL_462_Triana"
WTA$study <- "BM_Healthy_Triana"

bm$label <- bm$predicted.id
BM_All$label <- BM_All$predicted.id
WTA$label <- Idents(WTA)

bm$Sample <- paste0("VG_", bm$Sample)
BM_All$Sample <- paste0("TR_", BM_All$Batch)
WTA$Sample <- "TR_WTA"

integration.list <- list(bm = bm, WTA = WTA, BM_All = BM_All)

# normalize and identify variable features for each dataset independently
integration.list <- lapply(X = integration.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = integration.list)

# find anchors
immune.anchors <- FindIntegrationAnchors(object.list = integration.list, anchor.features = features)

# 'integrated' data assay
immune.combined <- IntegrateData(anchorset = immune.anchors)

saveRDS(immune.combined, file = "data/Integrated_TRI_VG_Seurat.RDS")

DimPlot(WTA)
```




```{r}
# pseudobulks
pb.sum <- as.data.frame(AggregateExpression(immune.combined, group.by = "label", assays = "integrated"))
pb.avg <- as.data.frame(AverageExpression(immune.combined, group.by = "label", assays = "integrated"))

colnames(pb.avg) <- gsub("integrated.","", colnames(pb.avg))
colnames(pb.sum) <- gsub("integrated.","", colnames(pb.sum))

l22 <- read.csv("data/LM22.txt", sep = "\t", row.names = 1)
```


```{r TCGA data}
TCGA <- read.csv("data/TCGA/laml.rnaseq.179_v1.0_gaf2.0_read_count_matrix.txt.tcgaID.txt", sep = "\t")

# Just get the gene symbols
TCGA$GeneID <- strsplit(TCGA$GeneID, "|", fixed = T) %>% map_chr(1)

# Remove unknown 
TCGA <- TCGA[TCGA$GeneID != "?", ]

# Order genes according to their standard deviation in decreasing order
TCGA <- TCGA [rev(order(apply(TCGA[,-1], 1, stats::sd))),]

# Remove duplicated genes
TCGA <- TCGA [!duplicated(TCGA[,1]),]

# Make the gene names the row names
rownames(TCGA) <- TCGA[,1]

# Remove the genes
TCGA <- TCGA[,-1]
```


```{r TCGA meta data}
TCGA.meta <- read.csv("data/TCGA/clinical_patient_laml.tsv", sep = "\t")

TCGA.meta[,1]<- gsub("-", ".",TCGA.meta[,1])

# get only patients with RNA-seq
TCGA.meta <- TCGA.meta[TCGA.meta[,1] %in% colnames(TCGA),]

# sort to same order to data
TCGA.meta <- TCGA.meta[match(colnames(TCGA),TCGA.meta[,1]),]

rownames(TCGA.meta) <- TCGA.meta[,1]

# separate abnormalities into different columns
TCGA.meta <- TCGA.meta %>% separate("cytogenetic_abnormality", c(paste0("cytogenetic_abnormality", c(1:4))), sep = "\\|")
```

```{r}
source("utils/CIBERSORT.R")

abseq.genelist <- read_excel("data/abseq_462_gene_list.xlsx")

intersected.genes <- intersect(rownames(pb), abseq.genelist$Gene)


prop.TCGA <- CIBERSORT(sig_matrix = pb[intersected.genes,], mixture_file = TCGA, perm = 100, QN = F)


# cytogenetic changes
cyto.loc <- paste0("cytogenetic_abnormality", c(1:4, "_other"))

# remove weird stuff from cytogenetic list
cyto.list <- unique(as.vector(t(TCGA.meta[,cyto.loc])))
cyto.list <- setdiff(cyto.list, c("NA", "[Not Available]", "no", "No", "Yes", "Normal", "NO", NA))
  
TCGA.cyto <- TCGA.meta[,cyto.loc]

cyto.annotations <- lapply(cyto.list, function(x){
  ifelse(rowSums(TCGA.cyto == x, na.rm = T) > 0, 1, 0)
}) %>% do.call(cbind, .) %>% as.data.frame

colnames(cyto.annotations) <- cyto.list
rownames(cyto.annotations) <- rownames(TCGA.meta)

colnames(cyto.annotations)[8] <- "Complex"



breaksList = seq(0,0.5, by = .001)
pheatmap.colors <- colorRampPalette((brewer.pal(n = 7, name = "Reds")))(length(breaksList))
pdf("output/TCGA_CIBERSORT_pseudobulk_cytogenetic_meta_data.pdf", width =7, height = 5)

pheatmap(prop.TCGA[,1:length(unique(Idents(bm)))],
       cluster_cols = T, color = pheatmap.colors, annotation_row = cyto.annotations,
       breaks = breaksList, show_rownames = F, show_colnames = T, legend = T, annotation_legend = F, fontsize = 6)
dev.off()

breaksList = seq(-3,3, by = .001)
pheatmap.colors <- colorRampPalette(rev(brewer.pal(n = 7, name = "PuOr")))(length(breaksList))
pdf("output/TCGA_CIBERSORT_pseudobulk_cytogenetic_meta_data_znorm.pdf", width =7, height = 5)

pheatmap(prop.TCGA[,1:length(unique(Idents(bm)))], scale = "row",
       cluster_cols = T, color = pheatmap.colors, annotation_row = cyto.annotations,
       breaks = breaksList, show_rownames = F, show_colnames = T, legend = T, annotation_legend = F, fontsize = 6)
dev.off()

breaksList = seq(-3,3, by = .001)
pheatmap.colors <- colorRampPalette(rev(brewer.pal(n = 7, name = "PuOr")))(length(breaksList))
pdf("output/TCGA_CIBERSORT_pseudobulk_cytogenetic_meta_data_znorm_patient.pdf", width =7, height = 5)

pheatmap(prop.TCGA[,1:length(unique(Idents(bm)))], scale = "column",
       cluster_cols = T, color = pheatmap.colors, annotation_row = cyto.annotations,
       breaks = breaksList, show_rownames = F, show_colnames = T, legend = T, annotation_legend = F, fontsize = 6)
dev.off()

```





```{r}
bm.umap <- bm@reductions$umap@cell.embeddings

bm.idents <- Idents(bm)

df <- data.frame(cbind(bm.idents = as.vector(bm.idents), bm.umap)) 

for (i in seq_len(nrow(prop.TCGA))){
    
    patient <- data.frame(value = prop.TCGA[i ,1:length(unique(Idents(bm)))], stringsAsFactors = T)
    
    patient.df <- merge(df, patient, by.x = "bm.idents", by.y = 0)
    
    patient.name <- rownames(prop.TCGA)[i]
    
    # shuffle 
    patient.df <- patient.df[sample(nrow(patient.df)),]
    
    ggplot(patient.df, aes(as.numeric(UMAP_1), as.numeric(UMAP_2), color = as.numeric(value)*100)) + geom_point() + scale_colour_gradientn(values = seq(0,100), colors = viridis(100)) + theme.gg + labs(color = "Cell type %", title = patient.name) + xlab("UMAP 1") + ylab("UMAP 2") 
    
    ggsave(paste0("output/Patient_conditions/TCGA/CIBERSORT_Pseudobulk/", patient.name, ".pdf"))
}

```


```{r TCGA residual analyses}
X <- pb[intersected.genes, ]

betaHat <-  prop.TCGA[,1:length(unique(Idents(bm)))]

yhat <- as.matrix(X) %*% t(as.matrix(betaHat))

y <- TCGA[intersected.genes, ]

res <- y - yhat



# p values could be between 0-1, therefore -log10(p) will be (0, +Inf)
breaksList = seq(-5, 5, by = .001)
pheatmap.colors <- colorRampPalette(rev(brewer.pal(n = 7, name = "PuOr")))(length(breaksList))
pdf("output/TCGA_CIBERSORT_pseudobulk_residual_with_meta_data.pdf", width = 10, height = 6)
pheatmap(t(res[rowSums(is.na(res)) == 0,]), annotation_row = cyto.annotations, scale = "row",
         color = pheatmap.colors, breaks = breaksList,
           show_rownames = F, show_colnames = F, legend = T, annotation_legend = T, fontsize = 6, 
           annotation_colors = mycolors)
dev.off()

```

```{r}
source("utils/wrangleMat.R")
All.AML.count <- read.csv("data/Other studies/combat-seq_corrected_all/count_matrix_GDC_LUMC_AML_g.csv")
All.AML.meta <- read.csv("data/Jeppe/meta_GDC_LUMC_AML.csv", row.names = 1)

# the order is the same
colnames(All.AML.count) <- c("Genenames", All.AML.meta[,"ID"])

All.AML.count <- wrangleMat(All.AML.count)


# ens to symbol map
ens2gene <- cinaR::grch38
m <- match(rownames(All.AML.count), ens2gene$ensgene)
mapped.genes <- ens2gene$symbol[m]

# duplicated name/NA/mitochondrial genes
removed.genes <- duplicated(mapped.genes) | is.na(mapped.genes) | grepl("^MT", mapped.genes)

All.AML.count <- All.AML.count[!removed.genes,]
rownames(All.AML.count) <- mapped.genes[!removed.genes]


prop.avg.all <- CIBERSORT(sig_matrix = pb.avg, mixture_file = All.AML.count, perm = 100, QN = F)
prop.sum.all <- CIBERSORT(sig_matrix = pb.sum, mixture_file = All.AML.count, perm = 100, QN = F)
prop.l22.all <- CIBERSORT(sig_matrix = l22, mixture_file = All.AML.count, perm = 100, QN = F)

colnames(prop.avg.all) <- gsub("integrated.","", colnames(prop.avg.all))
colnames(prop.sum.all) <- gsub("integrated.","", colnames(prop.sum.all))

save(prop.avg.all, prop.sum.all, prop.l22.all, l22, pb.avg, pb.sum, file = "cache/pseudobulk_props_all.RDS")
```


```{r}
pdiag <- All.AML.meta$primary_diagnosis

pdiag[is.na(pdiag)] <- "Unknown"

cyto.annotations <- model.matrix(~ 0 + pdiag) %>% as.data.frame


rownames(cyto.annotations) <- All.AML.meta[,"ID"]
colnames(cyto.annotations) <- gsub("pdiag", "", colnames(cyto.annotations))


df.anno.color <- data.frame(names = rep(colnames(cyto.annotations), each = 2), ops = rep(c(0,1), ncol(cyto.annotations)), 
                            colors = as.vector(rbind("#FCFCFC", "#FF0000")))



mycolors <- split(df.anno.color$colors, df.anno.color$names)
mycolors <- lapply(mycolors, function(x){names(x) <- as.factor(c("0", "1"));return(x)})


cyto.annotations <- cbind(cyto.annotations, All.AML.meta[, c("sample_type","gender", "blasts", "study")])



# pseudobulk with average profiles
pdf("output/All_studies_CIBERSORT_pseudobulk_avg_with_meta_data.pdf", width = 14, height = 6)
# p values could be between 0-1, therefore -log10(p) will be (0, +Inf)
breaksList = seq(0, max(prop.avg.all[,colnames(pb.avg)]), by = .001)
pheatmap.colors <- colorRampPalette(rev(brewer.pal(n = 7, name = "PuOr")))(length(breaksList))

pheatmap(prop.avg.all[,colnames(pb.avg)], cluster_cols = F, color = pheatmap.colors, annotation_row = cyto.annotations,
           breaks = breaksList, show_rownames = F, show_colnames = T, legend = T, annotation_legend = T, fontsize = 6, 
           annotation_colors = mycolors)
dev.off()


# pseudobulk with average profiles - znorm over patients
pdf("output/All_studies_CIBERSORT_pseudobulk_avg_with_meta_data_znorm.pdf", width = 14, height = 6)
# p values could be between 0-1, therefore -log10(p) will be (0, +Inf)
breaksList = seq(-3, 3, by = .001)
pheatmap.colors <- colorRampPalette(rev(brewer.pal(n = 7, name = "PuOr")))(length(breaksList))

pheatmap(prop.avg.all[,colnames(pb.avg)], cluster_cols = F, color = pheatmap.colors, annotation_row = cyto.annotations,
           breaks = breaksList, show_rownames = F, show_colnames = T, legend = T, annotation_legend = T, fontsize = 6, 
           annotation_colors = mycolors, scale = "row")
dev.off()

pdf("output/All_studies_CIBERSORT_pseudobulk_sum_with_meta_data.pdf", width = 14, height = 6)
breaksList = seq(0, max(prop.sum.all[,colnames(pb.sum)]), by = .001)
pheatmap.colors <- colorRampPalette(rev(brewer.pal(n = 7, name = "PuOr")))(length(breaksList))

pheatmap(prop.sum.all[,colnames(pb.sum)], cluster_cols = F, color = pheatmap.colors, annotation_row = cyto.annotations,
           breaks = breaksList, show_rownames = F, show_colnames = T, legend = T, annotation_legend = T, fontsize = 6, 
           annotation_colors = mycolors)
dev.off()

pdf("output/All_studies_CIBERSORT_l22_with_meta_data.pdf", width = 10, height = 6)
breaksList = seq(0, max(prop.l22.all[,colnames(l22)]), by = .001)
pheatmap.colors <- colorRampPalette(rev(brewer.pal(n = 7, name = "PuOr")))(length(breaksList))

pheatmap(prop.l22.all[,colnames(l22)], cluster_cols = F, color = pheatmap.colors, annotation_row = cyto.annotations,
           breaks = breaksList, show_rownames = F, show_colnames = T, legend = T, annotation_legend = T, fontsize = 6, 
           annotation_colors = mycolors)
dev.off()
```

```{r Remove AML patients from UMAP / Loading}
immune.combined <- readRDS("data/Integrated_TRI_VG_Seurat.RDS")

DefaultAssay(immune.combined) <- "integrated"
Idents(immune.combined) <- "label"

immune.combined <- subset(immune.combined, 
                          idents = c("Doublet and Triplets"), 
                          invert = T)
```


```{r Remove AML patients from UMAP / Seurat}
# Run the standard workflow for visualization and clustering
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)

pdf("output/UMAP_Integrated_cell_type_labeled.pdf", width = 8, height = 6)
DimPlot(immune.combined, label = T, repel = T, label.size = 3, shuffle = T) + theme.gg & NoLegend()
dev.off()

pdf("output/UMAP_Integrated_sample_labeled.pdf", width = 8, height = 6)
DimPlot(immune.combined, group.by = "Sample", shuffle = T) + theme.gg
dev.off()


pdf("output/UMAP_Integrated_study_labeled.pdf", width = 8, height = 6)
DimPlot(immune.combined, group.by = "study", shuffle = T) + theme.gg
dev.off()

features <- c("HBB","PPBP","CD14","CD34","MEIS1","S100A8","LYZ","CST3","CD1C","IL7R","FCER1G","FCGR3A","CD3D","CD3E","CD8A","CD8B","GZMA","GZMB","GZMH","GZMK","NKG7","MS4A1","CD79A","MZB1","JCHAIN","LILRA4","IRF7","IFI44L","ISG15","IFI6","CD4","B3GAT1","CD83","KLRB1","CD28","CD27","CCR5","MKI67","CD38","FOXP3","PF4","CLU")

pdf("output/Dotplot_Integrated_feautres.pdf", width = 16, height = 10)
DotPlot(immune.combined, features = features, dot.scale = 4, cluster.idents = T) + 
  scale_colour_gradient2(low = "#4575B4FF", mid = "#FFFFFF", high = "#A50026FF", midpoint = 0) + 
  theme(axis.text.x = element_text(angle = 45, hjust=1))
dev.off()
```


```{r pseudobulk from integrated cells}
pb.sum <- as.data.frame(AggregateExpression(immune.combined, assays = "integrated"))
pb.avg <- as.data.frame(AverageExpression(immune.combined, assays = "integrated"))

colnames(pb.sum) <- unique(Idents(immune.combined))
colnames(pb.avg) <- unique(Idents(immune.combined))

```



```{r Number of cell per cell type / Integrated}
pdf("output/Integrated_number_of_cells.pdf", width = 10, height = 6)
p2 <- immune.combined@meta.data%>% dplyr::count_("label") %>% ggplot(aes(x =reorder(label, -n), y = n)) + geom_bar(stat = "identity") + scale_fill_manual(values = c("#ad001a")) +  
  theme.gg + labs(title = "Integrated (Triana + Van Galen)",y = "Number of cells", x = "") + theme(axis.text.x = element_text(angle = 45, hjust=1)) 
  
p2
dev.off()
```


```{r control experiment}
cell.type.order <- 
  immune.combined@meta.data%>% dplyr::count_("label") %>% arrange(-n) %>% pull(label) 

cell.type.order.250 <- 
  immune.combined@meta.data%>% dplyr::count_("label") %>% arrange(-n) %>% filter(n > 250)

xmat <- immune.combined@assays$integrated

# exponentiate the data to non-log scale
xmat@data <- expm1(xmat@data)

xmeta <- immune.combined@meta.data
xmeta$Cell <- rownames(xmeta)

sample.proportions <- seq(0.5, 1, 0.1)
total.cells <- c(1000)


C.eset <- Biobase::ExpressionSet(assayData = as.matrix(xmat@data), phenoData = Biobase::AnnotatedDataFrame(xmeta))


lapply(sample.proportions, function(sample.proportion){
  lapply(total.cells,  function(total.cell){
    
    sim.true <-  NULL
    sim.bulks <- lapply(cell.type.order, function(x){
      
      real.val <- xmeta[xmeta$label == x,] %>% 
        slice_sample(n = sample.proportion * total.cell, replace = T)
      
      noise <- xmeta[xmeta$label != x,] %>% 
        add_count(label) %>% 
        mutate (n = 1/n) %>% 
        slice_sample(n = ((1-sample.proportion) * total.cell),weight_by = n, replace = T) %>% 
        dplyr::select(-n)
      
      cells <- rbind(real.val, noise)
      
      sim.true[[x]] <<- table(cells$label)/sum(table(cells$label))
      
      sim.bulk <- rowSums(xmat[, cells$Cell])
      
      return(sim.bulk)
    }) %>% do.call(cbind, .) %>% as.data.frame
    
    colnames(sim.bulks) <- cell.type.order
    
    # # Simulated bulks self deconvolution
    # sim.results <- CIBERSORT((pb.sum), (sim.bulks), perm = 1000, QN = F)
    
    # calculate overall rmse

    # sometimes there are minus values
    sim.bulks[sim.bulks <0] <- 0
    T.eset <- ExpressionSet(assayData = as.matrix(sim.bulks))
    
    sim.results <- music_prop(bulk.eset = T.eset, sc.eset = C.eset, clusters = 'label',
                                                markers = NULL, normalize = FALSE, samples = 'Sample', 
                                                verbose = F)
    
    # total.rmse <- lapply(cell.type.order, function(x){
    #   
    #   y <- sim.true[[x]][cell.type.order] 
    #   yhat <- sim.results[x, cell.type.order]
    #   
    #   error <- y - yhat
    #   
    #   sum(error^2, na.rm = T)
    # }) %>% unlist %>% sum
    
    music.results <- sim.results$Est.prop.weighted
    
    missing.cols <- cell.type.order[!cell.type.order %in% colnames(music.results)]
    
    new.order <- setdiff(cell.type.order, missing.cols)
    
    pdf(paste0("output/Integrated_pseudobulk_deconv_Music_", sample.proportion,"prop_",total.cell,"cells.pdf"), width = 12, height = 12)
    pheatmap(music.results[new.order,new.order], cluster_rows = F, cluster_cols = F,
             color = pheatmap.colors, breaks = breaksList, border_color = NA, display_numbers = T, fontsize = 7,
             cellwidth = 15, cellheight = 15)
    dev.off()
        
    # 
    # breaksList = seq(0,1, by = .001)
    # pheatmap.colors <- colorRampPalette((brewer.pal(n = 7, name = "Blues")))(length(breaksList))
    # pdf(paste0("output/Integrated_pseudobulk_deconv_CIBERSORT_", sample.proportion,"prop_",total.cell,"cells.pdf"), width = 12, height = 12)
    # pheatmap(sim.results[cell.type.order, cell.type.order], cluster_cols = F, cluster_rows = F, 
    #          color = pheatmap.colors, breaks = breaksList, border_color = NA, display_numbers = T, fontsize = 7,
    #          cellwidth = 15, cellheight = 15)
    # dev.off()
    
    # return(total.rmse)
    
  })
})

total.rmse.mat <- t(matrix(unlist(total.rmse), nrow = length(total.cells)) )
rownames(total.rmse.mat) <- sample.proportions
colnames(total.rmse.mat) <- total.cells

pheatmap((total.rmse.mat), cluster_rows = F, cluster_cols = F)
```

```{r Simple bulk mixing / deconvolution}
  
sim.bulks <- lapply(colnames(pb.sum), function(x){
  
  real.val <- pb.sum[,x, drop = F]
    
  noise <- rowSums(setdiff(pb.sum, real.val)*1/3)
  
  sim.bulk <- real.val + noise
  
  return(sim.bulk)
}) %>% do.call(cbind, .) %>% as.data.frame

# Simulated bulks self deconvolution
sim.results <- CIBERSORT(pb.sum, sim.bulks, perm = 1000, QN = F)

pheatmap.val <- sim.results[,1:(ncol(sim.results)-2)]

pheatmap.colors <- colorRampPalette((brewer.pal(n = 7, name = "Blues")))(length(breaksList))
pdf("output/Integrated_mix_pseudobulk_deconv_CIBERSORT.pdf", width = 10, height = 10)
p70 <- pheatmap(pheatmap.val[cell.type.order, cell.type.order], cluster_cols = F, cluster_rows = F, 
         color = pheatmap.colors, breaks = breaksList, border_color = NA, display_numbers = T, fontsize = 7,
         cellwidth = 15, cellheight = 15)

p70
dev.off()
```



```{r L22 subset trials}
cell.types <- colnames(l22)
  
sim.bulks <- lapply(cell.types, function(x){
  
  real.val <- l22[,x, drop = F]
    
  noise <- rowSums(setdiff(l22, real.val)*1/3)
  
  sim.bulk <- real.val + noise
  
  return(sim.bulk)
}) %>% do.call(cbind, .) %>% as.data.frame

sim.results <- CIBERSORT(sig_matrix = l22, mixture_file = sim.bulks,perm = 1000, QN = F)


pheatmap.val <- sim.results[,1:(ncol(sim.results)-2)]

breaksList = seq(0,1, by = .01)
pheatmap.colors <- colorRampPalette((brewer.pal(n = 7, name = "Blues")))(length(breaksList))
pdf("output/Integrated_L22_deconv_CIBERSORT.pdf", width = 12, height = 12)
p70 <- pheatmap(pheatmap.val , cluster_cols = F, cluster_rows = F, 
         color = pheatmap.colors, breaks = breaksList, border_color = NA, fontsize = 7,
         cellwidth = 20, cellheight = 20 , display_numbers = T )

p70
dev.off()
```



```{r manton 40K for reference}
# install.packages("~/Downloads/hcabm40k.SeuratData_3.0.0.tar.gz", repos = NULL, type = "source")

library(hcabm40k.SeuratData)
data("hcabm40k")

hcabm40k <- UpdateSeuratObject(hcabm40k)

hcabm40k[["percent.mt"]] <- PercentageFeatureSet(hcabm40k, pattern = "^MT-")
hcabm40k <- subset(hcabm40k, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

hcabm40k <- NormalizeData(hcabm40k)
hcabm40k <- FindVariableFeatures(object = hcabm40k)
hcabm40k <- ScaleData(hcabm40k, verbose = FALSE)
hcabm40k <- RunPCA(hcabm40k, features = VariableFeatures(hcabm40k),verbose = FALSE)
hcabm40k <- RunUMAP(hcabm40k, dims = 1:50)

pdf("output/UMAP_Manton_samples.pdf", width = 8, height = 6)
DimPlot(hcabm40k, shuffle = T) + theme.gg
dev.off()
```

```{r query WTA for manton}
WTA <- readRDS("data/Abseq/WTA_projected.rds")

DefaultAssay(WTA) <- "RNA"
WTA$label <- Idents(WTA)

WTA.anchors <- FindTransferAnchors(reference = WTA, query = hcabm40k, 
    dims = 1:30, reference.reduction = "pca")
predictions <- TransferData(anchorset = WTA.anchors, refdata = Idents(WTA), 
    dims = 1:30)
hcabm40k <- AddMetaData(hcabm40k, metadata = predictions)
```


```{r plot predicted labels for manton}
library(ggtext)
Idents(hcabm40k) <- "predicted.id"

pdf("output/UMAP_Manton_label_transferred.pdf", width = 5, height = 5)
p1 <- DimPlot(hcabm40k, group.by = "predicted.id", label = T, repel = T, label.size = 2.4)  + 
  theme.gg  + 
  labs(title = "**Manton BM Dataset - 30782 cells**", subtitle = "annotated using healthy Triana *et al.* sample") + 
  theme(plot.title = element_markdown(), 
        plot.subtitle = element_markdown(),
        legend.position = "none")
p1 
dev.off()
```


```{r}
pdf("output/Manton_number_of_predicted_cells.pdf", width = 8, height = 6)
p2 <- hcabm40k@meta.data %>% dplyr::count_("predicted.id") %>% ggplot(aes(x =reorder(predicted.id, -n), y = n, fill = n >= 100)) + geom_bar(stat = "identity") + scale_fill_manual(values = c("#999999", "#ad001a")) + labs(fill = ">= 100") + 
  theme.gg + labs(title = "Manton transferred labels",y = "Number of cells", x = "") + theme(axis.text.x = element_text(angle = 45, hjust=1)) 
  
p2
dev.off()
```


```{r}
meta <- hcabm40k@meta.data

meta$cell <- rownames(meta)

cell.types.hca40k <- unique(meta$predicted.id)

sample.proportion <- 0.7
total.cell <- 1e3

sim.bulks <- lapply(cell.types.hca40k, function(x){
  
  real.val <- xmeta[xmeta$label == x,] %>% 
    slice_sample(n = sample.proportion * total.cell, replace = T)
  
  noise <- xmeta[xmeta$label != x,] %>% 
    add_count(label) %>% 
    mutate (n = 1/n) %>% 
    slice_sample(n = ((1-sample.proportion) * total.cell),weight_by = n, replace = T) %>% 
    dplyr::select(-n)
  
  cells <- rbind(real.val, noise)
  
  sim.true[[x]] <<- table(cells$label)/sum(table(cells$label))
  
  sim.bulk <- rowSums(xmat[, cells$Cell])
  
  return(sim.bulk)
}) %>% do.call(cbind, .) %>% as.data.frame

colnames(sim.bulks) <- cell.types.hca40k
    

sim.bulks[sim.bulks <0] <- 0
T.eset <- ExpressionSet(assayData = as.matrix(sim.bulks))

sim.results <- music_prop(bulk.eset = T.eset, sc.eset = C.eset, clusters = 'label',
                                            markers = NULL, normalize = FALSE, samples = 'Sample', 
                                            verbose = F)


weights <- sim.results$Est.prop.weighted

pdf("output/Music_hca40k_sc_simulation_results.pdf", width = 12, height = 12)
pheatmap(weights[intersect(cell.type.order, cell.types.hca40k),intersect(cell.type.order, colnames(weights))], 
         cluster_cols = F, cluster_rows = F, color = pheatmap.colors, display_numbers = T,
         cellwidth = 15, cellheight = 15, fontsize = 7, 
         border_color = NA)
dev.off()


```

```{r Simple mixing Manton}
pb.sum.manton <- as.data.frame(AggregateExpression(hcabm40k))

colnames(pb.sum.manton) <- unique(Idents(hcabm40k))

sim.bulks.manton <- lapply(colnames(pb.sum.manton), function(x){
  
  real.val <- pb.sum.manton[,x, drop = F]
  noise <- rowSums(setdiff(pb.sum.manton, real.val)*1/3)
  
  sim.bulk <- real.val + noise
  
  return(sim.bulk)
}) %>% do.call(cbind, .) %>% as.data.frame


sim.results <- CIBERSORT(pb.sum, sim.bulks.manton, perm = 1000, QN = F)

pmap.vals <- sim.results[match(cell.type.order, rownames(sim.results)),cell.type.order]

pmap.vals2 <- matrix((sprintf("%.2f", pmap.vals)), nrow = nrow(pmap.vals))
pmap.vals2[is.na(pmap.vals2)] <- ""

pdf("output/CIBERSORT_Manton_mixing_deconvolution_results.pdf", width = 12, height = 12)
pheatmap(sim.results[match(cell.type.order, rownames(sim.results)),cell.type.order] , cluster_cols = F, cluster_rows = F, 
         color = pheatmap.colors, breaks = breaksList, border_color = NA,
         cellwidth = 20, cellheight = 20 , display_numbers = pmap.vals2 )
dev.off()

```

```{r select important mutations }
mutations <- c("NPM1", "DNMT3A","FLT3")
```


```{r TCGA pseudobulk deconv}

count.TCGA <- read.csv("data/Other studies/TCGA/TCGA_ht_seq.csv")

count.TCGA <- wrangleMat(count.TCGA)

mut.TCGA <- read.csv("data/Other studies/TCGA/TCGA_mutations_2_oh_meta.csv", row.names = 1)

meta.TCGA <- read.csv("data/Other studies/TCGA/TCGA_ht_seq_meta.csv", row.names = 1)

# ens to symbol map
ens2gene <- cinaR::grch38
m <- match(rownames(count.TCGA), ens2gene$ensgene)
mapped.genes <- ens2gene$symbol[m]

# duplicated name/NA/mitochondrial genes
removed.genes <- duplicated(mapped.genes) | is.na(mapped.genes) | grepl("^MT", mapped.genes)

count.TCGA <- count.TCGA[!removed.genes,]
rownames(count.TCGA) <- mapped.genes[!removed.genes]


# deconv.TCGA <- CIBERSORT(pb.sum, count.TCGA, perm = 1000, QN = F)

T.eset <- ExpressionSet(assayData = as.matrix(count.TCGA))

deconv.TCGA <- music_prop(bulk.eset = T.eset, sc.eset = C.eset, clusters = 'label',
                                            markers = NULL, normalize = FALSE, samples = 'Sample', 
                                            verbose = F)$Est.prop.weighted

ann.row.TCGA <- cbind(mut.TCGA[,mutations], Blast = meta.TCGA[,"BM_blasts"], Survival = (meta.TCGA[,"overal_survival"]) )

# pdf("output/CIBERSORT_TCGA_deconvolution_via_integrated_pseudobulk.pdf", width = 12, height = 12)
# pheatmap(deconv.TCGA [, intersect(cell.type.order, colnames(deconv.TCGA))], cluster_cols = F, cluster_rows = T, annotation_row = ann.row.TCGA,
#          color = pheatmap.colors, breaks = breaksList, border_color = NA, fontsize_row = 5)
# dev.off()

hc.TCGA <- hclust(dist(deconv.TCGA), method = "complete")


breaksList = seq(0,1, by = .001)
pheatmap.colors <- colorRampPalette((brewer.pal(n = 7, name = "Blues")))(length(breaksList))
pdf("output/Music_TCGA_deconvolution_via_integrated_pseudobulk.pdf", width = 12, height = 12)
pheatmap(deconv.TCGA [, intersect(cell.type.order, colnames(deconv.TCGA))], cluster_cols = F, cluster_rows = T, annotation_row = cbind(ann.row.TCGA, cluster = cutree(hc.TCGA, k = 3)),
         color = pheatmap.colors, breaks = breaksList, border_color = NA, fontsize_row = 5)
dev.off()
```


```{r TCGA Survival Analyses}
meta.TCGA <- cbind(meta.TCGA, cluster = cutree(hc.TCGA, k = 3))
meta.TCGA$status <- ifelse(meta.TCGA$event == "Alive", 0,1)

library(survminer)

km_trt_fit <- survfit(Surv(overal_survival, status) ~ cluster, data=meta.TCGA)

pdf("output/TCGA_Kaplan_Meier.pdf")
p <- ggsurvplot(km_trt_fit, 
           pval = T,
           # surv.median.line = "hv", # Add medians survival

           # Change legends: title & labels
           legend.title = "Cluster",
           legend.labs = c("C1", "C2", "C3"),
           
           palette = "Oranges",  
           
           # # Add risk table
           risk.table = TRUE,
           tables.height = 0.25,
           tables.theme = theme_cleantable(),
           
           ggtheme = theme_bw(base_size = 12))

print(p, newpage = F)
dev.off()
```

```{r TCGA Monocyte subset}
mono.ids <- meta.TCGA[meta.TCGA$cluster == 2,"ID"]

meta.TCGA.mono <- meta.TCGA[mono.ids,]

hc.TCGA.mono <- hclust(dist(deconv.TCGA[mono.ids,]), method = "complete")

meta.TCGA.mono$cluster.mono <- cutree(hc.TCGA.mono, k = 4)

pdf("output/Music_TCGA_Monocytes_deconvolution_via_integrated_pseudobulk.pdf", width = 12, height = 12)
pheatmap(deconv.TCGA [mono.ids, intersect(cell.type.order, colnames(deconv.TCGA))], 
         cluster_cols = F, cluster_rows = T, annotation_row = cbind(ann.row.TCGA[mono.ids,], cluster = cutree(hc.TCGA.mono, k = 4)),
         color = pheatmap.colors, breaks = breaksList, border_color = NA, fontsize_row = 5)
dev.off()

km_trt_fit <- survfit(Surv(overal_survival, status) ~ cluster.mono, data=meta.TCGA.mono)

pdf("output/TCGA_Kaplan_Meier_Monocytes.pdf")
p <- ggsurvplot(km_trt_fit, 
           pval = T,
           # surv.median.line = "hv", # Add medians survival

           # Change legends: title & labels
           legend.title = "Cluster",
           legend.labs = c("C1", "C2", "C3", "C4"),
           
           palette = "Oranges",  
           
           # # Add risk table
           risk.table = TRUE,
           tables.height = 0.25,
           tables.theme = theme_cleantable(),
           
           ggtheme = theme_bw(base_size = 12))

print(p, newpage = F)
dev.off()
```



```{r LUMC integrated pseudobulk deconvolution}
count.LUMC <- read.csv("data/Other studies/LUMC/LUMC_counts_htseq.csv")

count.LUMC <- wrangleMat(count.LUMC)

mut.LUMC <- read.csv("data/Other studies/LUMC/LUMC_mutations_oh_meta.csv", row.names = 1)

rownames(mut.LUMC) <- colnames(count.LUMC)

# Union FLT3 mutations to get a vector
mut.LUMC[,"FLT3"] <- ifelse(rowSums(mut.LUMC[,c("FLT3.ITD", "FLT3.TKD")] == 1) > 0, 1, 0)

meta.LUMC <- read.csv("data/Other studies/LUMC/meta_AML_LUMC.csv", row.names = 1)


# ens to symbol map
ens2gene <- cinaR::grch38
m <- match(rownames(count.LUMC), ens2gene$ensgene)
mapped.genes <- ens2gene$symbol[m]

# duplicated name/NA/mitochondrial genes
removed.genes <- duplicated(mapped.genes) | is.na(mapped.genes) | grepl("^MT", mapped.genes)

count.LUMC <- count.LUMC[!removed.genes,]
rownames(count.LUMC) <- mapped.genes[!removed.genes]


# deconv.LUMC <- CIBERSORT(pb.sum, count.LUMC, perm = 1000, QN = F)

T.eset <- ExpressionSet(assayData = as.matrix(count.LUMC))

deconv.LUMC <- music_prop(bulk.eset = T.eset, sc.eset = C.eset, clusters = 'label',
                                            markers = NULL, normalize = FALSE, samples = 'Sample', 
                                            verbose = F)$Est.prop.weighted

ann.row.LUMC <- cbind(mut.LUMC[,c(mutations,"FLT3.ITD", "FLT3.TKD")], Blast = meta.LUMC[,"blast_percentage"])

pdf("output/Music_LUMC_deconvolution_via_integrated_pseudobulk.pdf", width = 12, height = 12)
pheatmap(deconv.LUMC[,intersect(cell.type.order, colnames(deconv.LUMC))] , cluster_cols = F, cluster_rows = T,  annotation_row = ann.row.LUMC,
         color = pheatmap.colors, breaks = breaksList, border_color = NA, fontsize_row = 5)
dev.off()
```


```{r BEAT integrated pseudobulk deconvolution }
count.BEAT <- read.csv("data/Other studies/BEAT/BEAT_AML_ht_seq.csv")

count.BEAT <- wrangleMat(count.BEAT)

mut.BEAT <- read.csv("data/Other studies/BEAT/BEAT_AML_mutations.csv", row.names = 1)

meta.BEAT <- read.csv("data/Other studies/BEAT/BEAT_AML_ht_seq_meta.csv", row.names = 1)

meta.BEAT$blasts <- ifelse(grepl("Bone Marrow",meta.BEAT$sample_type), meta.BEAT$BM_blasts, meta.BEAT$PB_blasts)

# filter only AML patients
# meta.BEAT <- meta.BEAT[grepl("Acute myeloid leukemia", meta.BEAT$primary_diagnosis),]


# meta.blast.BEAT <- read.csv("data/meta_GDC_LUMC.csv")
# meta.blast.BEAT <- meta.blast.BEAT %>% filter(study == "BEAT")

# meta.BEAT <- merge(meta.BEAT, meta.blast.BEAT[,c("ID", "blasts")], by = "ID")

# ens to symbol map
ens2gene <- cinaR::grch38
m <- match(rownames(count.BEAT), ens2gene$ensgene)
mapped.genes <- ens2gene$symbol[m]

# duplicated name/NA/mitochondrial genes
removed.genes <- duplicated(mapped.genes) | is.na(mapped.genes) | grepl("^MT", mapped.genes)

count.BEAT <- count.BEAT[!removed.genes,meta.BEAT$ID]
rownames(count.BEAT) <- mapped.genes[!removed.genes]

# deconv.BEAT <- CIBERSORT(pb.sum, count.BEAT, perm = 100, QN = F)
T.eset <- ExpressionSet(assayData = as.matrix(count.BEAT))

deconv.BEAT <- music_prop(bulk.eset = T.eset, sc.eset = C.eset, clusters = 'label',
                                            markers = NULL, normalize = FALSE, samples = 'Sample', 
                                            verbose = F)$Est.prop.weighted



hc.BEAT <- hclust(dist(deconv.BEAT), method = "complete")
k.BEAT <- 3

ann.row.BEAT <- cbind(mut.BEAT[meta.BEAT$ID,mutations], Blast = meta.BEAT$blasts, Survival = (meta.BEAT$overal_survival))
breaksList = seq(0,1, by = .001)
pheatmap.colors <- colorRampPalette((brewer.pal(n = 7, name = "Blues")))(length(breaksList))
pdf("output/Music_BEAT_deconvolution_via_integrated_pseudobulk.pdf", width = 12, height = 12)
pheatmap(deconv.BEAT[,intersect(cell.type.order, colnames(deconv.BEAT))] , 
         cluster_cols = F, cluster_rows = T,  annotation_row = cbind(ann.row.BEAT, cluster = cutree(hc.BEAT, k =k.BEAT)),
         color = pheatmap.colors, breaks = breaksList, border_color = NA, fontsize_row = 5, clustering_method = "complete")
dev.off()
```

```{r BEAT Survival Analyses}
temp.BEAT <- cbind(meta.BEAT, cluster = cutree(hc.BEAT, k = k.BEAT))
temp.BEAT$status <- ifelse(temp.BEAT$event == "Dead", 1,0)

library(survminer)

km_trt_fit <- survfit(Surv(overal_survival, status) ~ cluster, data=temp.BEAT)

pdf("output/BEAT_Kaplan_Meier.pdf")
p <- ggsurvplot(km_trt_fit, 
           pval = T,
           # surv.median.line = "hv", # Add medians survival
          
           # Change legends: title & labels
           legend.title = "Cluster",
           legend.labs = paste0("C", 1:length(unique(temp.BEAT$cluster))),
           
           palette = "Oranges",  
           
           # # Add risk table
           risk.table = TRUE,
           tables.height = 0.25,
           tables.theme = theme_cleantable(),
           
           ggtheme = theme_bw(base_size = 12))

print(p, newpage = F)
dev.off()
```


```{r TARGET integrated pseudobulk deconvolution}
count.TARGET <- read.csv("data/Other studies/TARGET/TARGET_ht_seq.csv")

count.TARGET <- wrangleMat(count.TARGET)

# ens to symbol map
ens2gene <- cinaR::grch38
m <- match(rownames(count.TARGET), ens2gene$ensgene)
mapped.genes <- ens2gene$symbol[m]

# duplicated name/NA/mitochondrial genes
removed.genes <- duplicated(mapped.genes) | is.na(mapped.genes) | grepl("^MT", mapped.genes)

count.TARGET <- count.TARGET[!removed.genes,]
rownames(count.TARGET) <- mapped.genes[!removed.genes]


mut.TARGET <- read.csv("data/Other studies/TARGET/TARGET_mutations_df_3.csv", row.names = 1)



meta.TARGET <- read.csv("data/Other studies/TARGET/TARGET_ht_seq_meta.csv", row.names = 1)


# deconv.TARGET <- CIBERSORT(pb.sum, count.TARGET, perm = 100, QN = F)
T.eset <- ExpressionSet(assayData = as.matrix(count.TARGET))

deconv.TARGET <- music_prop(bulk.eset = T.eset, sc.eset = C.eset, clusters = 'label',
                                            markers = NULL, normalize = FALSE, samples = 'Sample', 
                                            verbose = F)$Est.prop.weighted


hc.TARGET <- hclust(dist(deconv.TARGET), method = "complete")
k.TARGET <- 4


ann.row.TARGET <- cbind(mut.TARGET[,colnames(mut.TARGET)%in%mutations], Blast = meta.TARGET[,"BM_blasts"], 
                        Survival = meta.TARGET$overal_survival)

pdf("output/Music_TARGET_deconvolution_via_integrated_pseudobulk.pdf", width = 12, height = 12)
pheatmap(deconv.TARGET[,intersect(cell.type.order, colnames(deconv.TARGET))] , 
         cluster_cols = F, cluster_rows = T,  annotation_row = cbind(ann.row.TARGET, Cluster = cutree(hc.TARGET, k = k.TARGET)),
         color = pheatmap.colors, breaks = breaksList, border_color = NA, fontsize_row = 5)
dev.off()

```
```{r survival analyses TARGET}
temp.target <- cbind(meta.TARGET, cluster = cutree(hc.TARGET, k = k.TARGET))
temp.target$status <- ifelse(temp.target$event == "Dead", 1,0)

library(survminer)

km_trt_fit <- survfit(Surv(overal_survival, status) ~ cluster, data=temp.target)

pdf("output/TARGET_Kaplan_Meier.pdf")
p <- ggsurvplot(km_trt_fit, 
           pval = T,
           # surv.median.line = "hv", # Add medians survival
          
           # Change legends: title & labels
           legend.title = "Cluster",
           legend.labs = paste0("C", 1:length(unique(temp.target$cluster))),
           
           palette = "Greys",  
           
           # # Add risk table
           risk.table = TRUE,
           tables.height = 0.25,
           tables.theme = theme_cleantable(),
           
           ggtheme = theme_bw(base_size = 12))

print(p, newpage = F)
dev.off()
```



```{r}
deconv.all <- rbind(deconv.TCGA, 
                    deconv.LUMC, 
                    deconv.BEAT,
                    deconv.TARGET)

deconv.all.list <- list( TCGA = deconv.TCGA, 
                    LUMC = deconv.LUMC, 
                    BEAT = deconv.BEAT,
                    TARGET = deconv.TARGET)


ann.row.all <- rbind.fill(cbind(ann.row.TCGA, Study = "TCGA"),
                          cbind(ann.row.LUMC, Study = "LUMC"), 
                          cbind(ann.row.BEAT, Study = "BEAT"),
                          cbind(ann.row.TARGET, Study = "TARGET"))

rownames(ann.row.all) <- rownames(deconv.all)

pdf("output/Music_ALL_deconvolution_via_integrated_pseudobulk.pdf", width = 12, height = 12)
pheatmap(deconv.all[,intersect(cell.type.order, colnames(deconv.all))] , cluster_cols = F, cluster_rows = T, 
         annotation_row = ann.row.all, show_rownames = F,
         color = pheatmap.colors, breaks = breaksList, border_color = NA, fontsize_row = 5)
dev.off()
```

```{r}
library(ggridges)

logitTransform <- function(p) { ifelse(p == 0,0,  log(p/(1-p))) }

deconv.LUMC.df <- deconv.LUMC %>% melt(.id = "Cell Type")
deconv.LUMC.df$logit <- logitTransform(deconv.LUMC.df$value)

pdf("output/LUMC_deconvolution_coef_distributions.pdf")
# ggplot(deconv.LUMC.df, aes(value, Var2, fill = Var2)) + geom_density_ridges(scale = 2,point_size = 0.1, jittered_points = T) + theme_bw() + xlab("Deconvolution coefficient") + ylab("") + theme(legend.position = "none") + xlim (c(0,1))

ggplot(deconv.all %>% melt(.id = "Cell Type"), aes(value, Var2, fill = Var2)) + geom_density_ridges(scale = 3,point_size = 0.01, jittered_points = T) + theme_bw() + xlab("Deconvolution coefficient") + ylab("") + theme(legend.position = "none") + xlim (c(0,1))

dev.off()
```



```{r linear model blast vs deconv}
load("cache/Integrated_sc_deconvolutions_of_bulks.Rdata")


meta.all <- rbind.fill(meta.TCGA, 
                       meta.LUMC, 
                       meta.BEAT,
                       meta.TARGET)


library(ggridges)

cell.type.order.new <- intersect(cell.type.order, colnames(deconv.all))


df <- cbind(deconv.all, ann.row.all)

df <- df[,c("Blast", "Study", cell.type.order.new)]

pdf("output/Blast_percentage_each_study.pdf", width = 8, height = 6)
ggplot(df, aes(x = Blast, y = Study, fill = stat(x))) + 
  geom_density_ridges_gradient(scale = 1, rel_min_height = 0.01, jittered_points = TRUE) +
  scale_fill_viridis(name = "Blast %", option = "C") + 
  theme.gg 
dev.off()


common.mutations <- 
  Reduce(intersect, list(colnames(mut.BEAT), 
                         colnames(mut.LUMC), 
                         colnames(mut.TARGET), 
                         colnames(mut.TCGA)))

mut.all <- rbind(mut.TCGA[,common.mutations], 
                 mut.LUMC[,common.mutations], 
                 mut.BEAT[,common.mutations],
                 mut.TARGET[,common.mutations])

mut.all.list <- list(TCGA = mut.TCGA[,common.mutations], 
                 LUMC = mut.LUMC[,common.mutations], 
                 BEAT = mut.BEAT[,common.mutations],
                 TARGET = mut.TARGET[,common.mutations])


p.vals <- lapply(cell.type.order.new, function(x){
  
  df <- cbind(y = deconv.all[,x], mut.all)
  p.vals <- sapply(df[,-1], function(x){summary(lm(df$y ~ x , data = df))$coefficients[-1,4]})
  # p.vals <- summary(lm(df$y ~ . , data = df))$coefficients[-1,4]
  return(p.vals)
})


names(p.vals) <- cell.type.order.new

p.vals <- data.frame(bind_rows(p.vals, .id = "Cell Type"), row.names = 1)

coefs <- lapply(cell.type.order.new, function(x){
  
  df <- cbind(y = deconv.all[,x], mut.all)
  coefs <- sapply(df[,-1], function(x){summary(lm(df$y ~ x , data = df))$coefficients[-1,1]})
  # p.vals <- summary(lm(df$y ~ . , data = df))$coefficients[-1,4]
  return(coefs)
})

names(coefs) <- cell.type.order.new

coefs <- data.frame(bind_rows(coefs, .id = "Cell Type"), row.names = 1) 

pmap.text <- ifelse(p.vals<0.05, ifelse(p.vals<0.01, ifelse(p.vals<0.001, "***", "**"),"*"), "")


breaksList = seq(0,12, by = .1)
pheatmap.colors <- colorRampPalette((brewer.pal(n = 7, name = "Reds")))(length(breaksList))
pdf("output/Common_Mutations_vs_Deconvolutions_one_by_one.pdf")
pheatmap(-log10(p.vals), display_numbers = pmap.text, cluster_rows = F, cluster_cols = F,
         breaks = breaksList, color = pheatmap.colors, number_color = "white", border_color = NA)
dev.off()

df.plot <-
merge(reshape2::melt(as.matrix(p.vals), value.name = "p.vals"),
      reshape2::melt(as.matrix(coefs) , value.name = "coefs"), by = c("Var1", "Var2"))

pdf("output/Common_Mutations_vs_Deconvolutions_with_coefs.pdf")
  p <- ggplot(df.plot, aes(Var2, (Var1), size = -log10(p.vals),
                      color = ifelse(coefs >0, "Positive", "Negative"),
                      label = ifelse(p.vals < 0.05, "*", ""))) + 
    geom_point() + 
    geom_text(size = 3, color = "white", nudge_y = -0.1) + 
    theme_bw(base_size = 10) + # ggtitle(label = s) + 
    scale_color_manual(values = c("blue", "red")) + labs (color = "Coefficient") + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylab("") + xlab("Common Mutations")
  
  print(p)
dev.off()
```


```{r blast levels vs }
library(ggside)
pdf("output/Blast_vs_Cell_type_props.pdf")
lapply(cell.type.order.new, function(x){
  ggplot(df, aes(df[,x], Blast)) + geom_point() + theme.gg + labs(title = x, x = "Cell type prop." ) + 
    geom_xsidedensity() + geom_ysidedensity() + 
    theme(axis.text.x = element_text(angle = 90, vjust = .5)) + geom_smooth(method = "lm")
}) 
dev.off()
```


```{r linear models for each study}
studies <- names(deconv.all.list)


results <- lapply(studies, function(s){
  
  p.vals <- lapply(cell.type.order.new, function(x){
    
    df <- cbind(y = deconv.all.list[[s]][,x], mut.all.list[[s]])
    
    # p.vals <- sapply(df[,-1], function(x){summary(lm(df$y ~ x , data = df))$coefficients[-1,4]})
    ## kruskal test is applied when y is numeric and x is a factor
    p.vals <- sapply(colnames(df)[-1], function(x) {
      
      if(sd(df[,x])>0) return(wilcox.test(as.formula(paste("y", x, sep=" ~ ")) , data = df)$p.value)
      else return(1)
    })
    
    qqp.vals <- lapply(p.vals, function(x){ifelse(length(x) == 0, return(NA), return(x)) })
    # p.vals <- summary(lm(df$y ~ . , data = df))$coefficients[-1,4]
    return(p.vals)
  })
  
  names(p.vals) <- cell.type.order.new
  
  p.vals <- data.frame(bind_rows(p.vals, .id = "Cell Type"), row.names = 1)
  
  coefs <- lapply(cell.type.order.new, function(x){
    
    df <- cbind(y = deconv.all.list[[s]][,x], mut.all.list[[s]])
    coefs <- sapply(df[,-1], function(x){summary(lm(df$y ~ x , data = df))$coefficients[-1,1]})
    
    coefs <- lapply(coefs, function(x){ifelse(length(x) == 0, return(NA), return(x)) })

    return(coefs)
  })
  
  names(coefs) <- cell.type.order.new
  
  coefs <- data.frame(bind_rows(coefs, .id = "Cell Type"), row.names = 1) 
  
  # pmap.text <- ifelse(p.vals<0.05, ifelse(p.vals<0.01, ifelse(p.vals<0.001, "***", "**"),"*"), "")
  # 
  # 
  # breaksList = seq(0,12, by = .1)
  # pheatmap.colors <- colorRampPalette((brewer.pal(n = 7, name = "Reds")))(length(breaksList))
  # pdf("output/Common_Mutations_vs_Deconvolutions_one_by_one.pdf")
  # pheatmap(-log10(p.vals), display_numbers = pmap.text, cluster_rows = F, cluster_cols = F,
  #          breaks = breaksList, color = pheatmap.colors, number_color = "white", border_color = NA)
  # dev.off()
  
  df.plot <-
  merge(reshape2::melt(as.matrix(p.vals), value.name = "p.vals"),
        reshape2::melt(as.matrix(coefs) , value.name = "coefs"), by = c("Var1", "Var2"))
  
  pdf(paste0("output/Common_Mutations_vs_Deconvolutions_with_coefs_",s, ".pdf"))
  p <- ggplot(df.plot, aes(Var2, (Var1), size = -log10(p.vals),
                      color = ifelse(coefs >0, "Positive", "Negative"),
                      label = ifelse(p.vals < 0.05, "*", ""))) + 
    geom_point() + 
    geom_text(size = 3, color = "white", nudge_y = -0.1) + 
    theme_bw(base_size = 10) + ggtitle(label = s) + 
    scale_color_manual(values = c("blue", "red")) + labs (color = "Coefficient") + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylab("") + xlab("Common Mutations")
  
  print(p)
  dev.off()
  
  return(list(p.vals = p.vals, coefs = coefs))
  
})


names(results) <- studies


p.overlap <- lapply(results, function(r){
  r$p.vals < 0.1
}) %>% Reduce("+", . )

p.overlap [is.na(p.overlap)] <- 0 



coef.overlap <- lapply(results, function(r){
  ifelse(r$coefs > 0 ,1, ifelse(is.na(r$coefs), NA, -1))
}) %>% Reduce("+", .)

coef.overlap[coef.overlap == -4] <- "Negative"
coef.overlap[coef.overlap ==  4] <- "Positive"

coef.overlap[!coef.overlap %in% c("Positive", "Negative")] <- NA


pdf("output/Common_Mutations_vs_Deconvolutions_same_direction_all_studies.pdf")
merge(coef.overlap %>% reshape2::melt(),
      p.overlap %>% reshape2::melt(), by = c("Var1", "Var2")) %>% 
  ggplot(aes(Var2, Var1,color = value.x, label = ifelse(!is.na(value.x), value.y, NA)))+ 
    geom_point(size = 3) + geom_text(size = 2, color = "white") + 
    theme_bw(base_size = 10) + 
    scale_color_manual(values = c("blue", "red")) + labs (color = "Same direction") + 
    ggtitle ("Common Changes", subtitle = "(TCGA, LUMC, BEAT, TARGET)") + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylab("") + xlab("Common Mutations")
dev.off()
```

```{r}
library(randomForest)

dat <- data.frame(cbind(y = mut.LUMC$NPM1 , deconv.LUMC))

fit <- randomForest(y ~ ., data = dat, importance = T)

summary(fit)

plot(factor(mut.LUMC$NPM1, labels = c("Normal", "Mutated")), predict(fit, data.frame(deconv.LUMC)))

importance(fit, scale = T)

plot(mut.TCGA$NPM1, predict(fit, data.frame(deconv.TCGA)))
```

